---
title: Three sets of random numbers
author: Cassandra Ortiz
output: html_document
---

```{r, here-i-am, include = FALSE}
here::i_am(
  "report.Rmd"
)
```

```{r, load-random-numbers, include = FALSE}
#! TO DO: 
#!   read random_numbers1 from output directory
random_numbers1 <- readRDS(
  here::here("output/random_numbers1.rds")
)
#! TO DO: 
#!   read random_numbers2 from output directory
random_numbers2 <- readRDS(
  here::here("output/random_numbers2.rds")
)
#! TO DO: 
#!   read random_numbers3 from output directory
random_numbers3 <- readRDS(
  here::here("output/random_numbers3.rds")
)
```

# Distribution 1
```{r, Distribution1-histogram}
#| fig.cap = "Distribution 1"
hist(random_numbers1, main = "Distribution 1", col = "steelblue")
```
# Distribution 2

```{r, Distribution2-histogram}
#| fig.cap = "Distribution 2"
hist(random_numbers2, main = "Distribution 2", col = "pink")
```

# Distribution 3

```{r, Distribution3-histogram}
#| fig.cap = "Distribution 3"
hist(random_numbers3, main = "Distribution 3", col = "purple")
```

